/*

 PLAYERDATA.C

 Map Source File.

 Info:
   Section       : 
   Bank          : 0
   Map size      : 2 x 2
   Tile set      : C:\Users\brady\Desktop\proj\assets\charactersprites.gbr
   Plane count   : 0.5 plane (4 bits)
   Plane order   : Tiles are continues
   Tile offset   : 0
   Split data    : No

 This file was generated by GBMB v1.8

*/

#define playerWidth 2
#define playerHeight 2
#define playerBank 0

unsigned char player[] =
{
  0x13,0x02
};

/* End of PLAYERDATA.C */
